[tools]
golang = "1.20.1"
node = "24.10.0"
rust = "1.89.0"
python = "3.10.5"
terraform = "1.7.1"
go = "1.22.1"
gradle = "8.0"
php = "8.3.4"
usage = "2.0.3"
ruby = "3.2.2"
java = "23.0.1"

[settings]
experimental = true

